export const words = [
  "Arthur Ashe",
  "Arthur Conan Doyle",
  "Arthur Guinness",
  "Arthur Miller",
  "Arthur Rimbaud",
  "Arthur Vera",
  "Arthur Schopenhauer",
  "Arthur H",
  "Arthur C. Clarke",
  "Arthur Zico",
  "Arthur Ashe",
  "Arthur Conan Doyle",
  "Arthur Guinness",
  "Arthur Miller",
  "Arthur Rimbaud",
  "Arthur Vera",
  "Arthur Schopenhauer",
  "Arthur H",
  "Arthur C. Clarke",
  "Arthur Zico",
  "Arthur Ashe",
  "Arthur Conan Doyle",
  "Arthur Guinness",
  "Arthur Miller",
  "Arthur Rimbaud",
  "Arthur Vera",
  "Arthur Schopenhauer",
  "Arthur H",
  "Arthur C. Clarke",
  "Arthur Zico",
  "Arthur Ashe",
  "Arthur Conan Doyle",
  "Arthur Guinness",
  "Arthur Miller",
  "Arthur Rimbaud",
  "Arthur Vera",
  "Arthur Schopenhauer",
  "Arthur H",
  "Arthur C. Clarke",
  "Arthur Zico",
  "Arthur Ashe",
  "Arthur Conan Doyle",
  "Arthur Guinness",
  "Arthur Miller",
  "Arthur Rimbaud",
  "Arthur Vera",
  "Arthur Schopenhauer",
  "Arthur H",
  "Arthur C. Clarke",
  "Arthur Zico",
];
